### ISSUE TITLE
Unable to have accepted encryption for Kakao 4.89

### ISSUE THREAD

**Issue by probperiplum** [barncastle/CookieRun-DJBF-Converter#1]
I have attempted to edit version 4.89 of Cookie Run for Kakao, specifically EquipmentDataCookieRun.djb, to have some integers changed and the game does read the DJBF header correctly but rejects the file as it detects it as tampered. I tried using every version and variant of AES with version codes paired with FastLZ (which I'm certain is used here in this version considering the compression ratio) and the game gives the same result.

As always, the app file can be found here: https://archive.org/download/cookierun-for-kakao-apk and the game can be tested via the "guest mode" button on the title screen. If a warning message of a police character appears, then the game has rejected it. I'm wondering if each version has a specific variant/shift; but investigation is much appreciated. 4.89 is the last version of the game to be moddable without needing to carry over assets from later versions not present to prevent crashing.

To me, the most important text files to specifially investigate are EqupimentDataCookieRun.djb, InnerSystemConfig.djb, and JellyMagicJellyStatData.djb; in that order. 

If you plan on attempting to find individual codes for each version of the game, it's worth noting that the offline "Guest Mode" was removed after version 6.13, so investigation for further versions is unnecessary.

**Comment by barncastle** [comment]
It appears there was a bug in the keychain whereby it was using the wrong AES encryption Key and IV which is now fixed. I've also changed the tool to print the version and flags of each file it decrypts to make things easier. You can find the new release [here](https://github.com/barncastle/CookieRun-DJBF-Converter/releases/latest). Hopefully this resolves the problem, unfortunately I'm unable to emulate version 4.89 so can't guarantee it does.

FYI version 4.89 files are all version 1 and use the "AES_ECB, FastLZ" flags i.e.
`.\cookierunconverter.exe -m encrypt -k kakao -v 1 -f "AES_ECB, FastLZ"`

**Comment by probperiplum** [comment]
I have tested the update and I can confirm that the game accepts the encryption!

The program itself still claims that it's running 1.0.0 and not 1.1 so that's a minor thing but otherwise that solves my quest. Thank you so much!

**Comment by ghost** [comment]
"investing further versions is unnecessary"

Didn't we have to try decrypt latest version of line cookierun?(6.1.3)

**Comment by probperiplum** [comment]
LINE uses the same encryption key as Kakao.
