### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [barncastle/CookieRun-DJBF-Converter#2]
C:\Users\user\Desktop\test>cookierunconverter.exe -m decrypt -k kakao
Decrypting CommandLine.dll
        Detected: [Version: 0300 Flags: ]

처리되지 않은 예외: System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.Exception: Checksum :: EE83E28E != 00000004
   위치: CookieRunDJBFConverter.DJBFConverter.Decrypt(String path)
   위치: CookieRunDJBFConverter.Program.<Run>d__1.MoveNext()
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: CookieRunDJBFConverter.Program.Main(String[] args)

I put EquipmentDataCookieRun.djb on test folder, but this error appear

**Comment by ghost** [comment]
solve issue with temp. I changed file name to "aEquipmentDataCookieRun.djb", and it worked. maybe it is related with file name alphabet order? but issue is issue so I will open it.

**Comment by barncastle** [comment]
> Decrypting CommandLine.dll

It looks like the program was attempting to decrypt CommandLine.dll - which isn't a djb file. 

By default the program decrypts all files within the current directory. I'll add some extra code to check that the input files are actually DJB and skip those that aren't. For the meantime you can use the -s filter to select specific files and/or extensions to process e.g.

`cookierunconverter.exe -m decrypt -k kakao -s "*.djb"` (Only decrypt files with a djb extension)

`cookierunconverter.exe -m decrypt -k kakao -s "EquipmentDataCookieRun.djb"` (Only decrypt EquipmentDataCookieRun.djb)

**Comment by barncastle** [comment]
I've added some extra code to detect the "DJBF" signature for files in the [latest version](https://github.com/barncastle/CookieRun-DJBF-Converter/releases/latest).

**Comment by ghost** [comment]
Decrypting CommandLine.dll

처리되지 않은 예외: System.ArgumentNullException: 값은 null일 수 없습니다.
매개 변수 이름: bytes
   위치: CookieRunDJBFConverter.Program.Main(String[] args)

**Comment by ghost** [comment]
seems like it does not solved

**Comment by barncastle** [comment]
There was a regression introduced from the UTF8 change where I didn't check if the file was valid or not. This is resolved by the latest version.
