### ISSUE TITLE
please fix this files

### ISSUE THREAD

**Issue by ghost** [barncastle/CookieRun-DJBF-Converter#3]
I'm talking about 6.04 (fixed)apk

Episode.djb
MapStageScenario_ep***.djb (I mean all episodes)
StageScenarioList.djb
StageThemeData.djb
CRXSoundFileList.djb
CRX.SoundEventList.djb
SoundFileList.djb

because I need to edit this for lookaround of fixing sound issue

**Comment by ghost** [comment]
+ editing not fully decrypted djb file(.bin file) with hxd and then encrypting works. leave this comment for who need this info

**Comment by barncastle** [comment]
Could you provide more details on the issue please?

I've just tested these and they're decrypting and encrypting fine for me. If decryption fails the program will error as the [checksums won't match](https://github.com/barncastle/CookieRun-DJBF-Converter/blob/master/CookieRunDJBFConverter/DJBFConverter.cs#L48).

Just to note, version 6.04 changed format from json files to a binary format with `uint32` length prefixed strings.

**Comment by ghost** [comment]
uint32? Then files are with weird characters are normal when using notepad? How can I edit files then?

**Comment by ghost** [comment]
And do you know what version started using uint32?

**Comment by barncastle** [comment]
>Then files are with weird characters are normal when using notepad? How can I edit files then?

You need to use a hex editor for these as they're not text files. The files have a structure like the below. Essentially each string has its length (as a 32 bit/4 byte number aka `uint32`) before it so each time you edit a string you need to update the length.

I've put together a [visual representation](https://ibb.co/S6WyJQH) from my hex editor which will hopefully help explain this. As you'll see, the first string (solid green) is "Cooltime" which is 8 characters long, the preceding 4 bytes (green outlined) are `08 00 00 00` which is `8` as 32 bit hex. If you were to change "Cooltime" to "ExampleString", which is 13 characters, you'd need to change the preceding hex bytes to `0D 00 00 00` which is `13` as 32 bit hex.

I assume these Entries map to the old json structures but someone else will need to investigate that. 

>And do you know what version started using uint32?

I'm not sure which version but probably from 6.02 - should be simple enough to check.

```
struct binaryDJB {
  uint32 entryCount;
  Entry entries[entryCount];
}

struct Entry {
  uint32 type;
  String strings[x]; // the amount varies by type
}

struct String {
  uint32 length;
  char text[length];
}
```

Hopefully this helps however as this is outside the scope of the project I'll be closing this issue.
