### ISSUE TITLE
how to solve unicode(korean) are broken?

### ISSUE THREAD

**Issue by ghost** [barncastle/CookieRun-DJBF-Converter#4]
[aEpisode_ko.zip](https://github.com/barncastle/CookieRun-DJBF-Converter/files/9730203/aEpisode_ko.zip)

I tried to decrypt this file but unicode characters are all broken. So idk how to edit it. or can you solve it on your side?

**Comment by ghost** [comment]
https://convertcodes.com/utf16-encode-decode-convert-string/

I used this site and I selected that  bin file and decode with utf-8 and it converted correctly. Maybe you didn't support utf-8?

**Comment by ghost** [comment]
https://dencode.com/

I am trying to use this site.

**Comment by barncastle** [comment]
This program works at a byte level and therefore has no concept of encoding - encoding is a text format specification. 

If you want I can change the output from raw blobs to UTF8 text files instead however I don't know if that will break/corrupt the 6.0.2+ binary DJBs or encoding?

**Comment by ghost** [comment]
Well if it will break, then I use limited method instead.

How to edit limited method?(for who need info) :
1. Copy broken korean to up dencode.com site
2. If you confirmed that is korean text, change with hxd, you need to becareful file size not to be changed(I know korean -> english edit but korean -> korean editing would be not possible if unicode does not supported, and only editied text length are possible within original text length.(i mean if original text length is 16, then you can't write more than 17))

**Comment by barncastle** [comment]
I've changed the decoded files to be converted to UTF8 in the [latest version](https://github.com/barncastle/CookieRun-DJBF-Converter/releases/latest). I don't have any way to test this at the moment so if you could try and let me know the outcome that'd be appreciated. If things break I'll revert this change.

**Comment by ghost** [comment]
Seems like it has problem, I didn't edit djb file and just decrypt, encrypt djb file but game crash.

**Comment by ghost** [comment]
> Well if it will break, then I use limited method instead.
> 
> How to edit limited method?(for who need info) :
> 
> 1. Copy broken korean to up dencode.com site
> 2. If you confirmed that is korean text, change with hxd, you need to becareful file size not to be changed(I know korean -> english edit but korean -> korean editing would be not possible if unicode does not supported, and only editied text length are possible within original text length.(i mean if original text length is 16, then you can't write more than 17))

maybe we need to use this method.

**Comment by barncastle** [comment]
I've forced UTF8 encoding on the decryption output and ASCII encoding on the encryption input which should negate this issue now. [See releases.](https://github.com/barncastle/CookieRun-DJBF-Converter/releases/latest)

Just to let you know, most hex editors (e.g. 010 Editor) support toggling between encoding standards for editing which may be easier than using various sites.

**Comment by ghost** [comment]
> Seems like it has problem, I didn't edit djb file and just decrypt, encrypt djb file but game crash.

no, this issue still appear on 1.3 version too. So I think you need to roll back.
